name: Mentoria Tech Web
on:
  push:
    branches:
      - main
jobs: 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_NEXTAUTH_URL: "https://mentoria.tech"
        envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        envkey_GH_APPLICATION_CLIENT_ID: ${{ secrets.GH_APPLICATION_CLIENT_ID }}
        envkey_GH_APPLICATION_CLIENT_SECRET: ${{ secrets.GH_APPLICATION_CLIENT_SECRET }}
        file_name: .env
    - name: Dependencies
      run: yarn && yarn add pg-native
    - name: Build
      run: yarn build
    - name: Serverless install
      run: npm install -g serverless && npm i -g @sls-next/serverless-component
    - name: Serverless deploy
      run: serverless --component=MentoriaTechWeb build && serverless --component=MentoriaTechWeb deploy 
      env:
        NEXTAUTH_URL: "https://mentoria.tech"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GH_APPLICATION_CLIENT_ID: ${{ secrets.GH_APPLICATION_CLIENT_ID }}
        GH_APPLICATION_CLIENT_SECRET: ${{ secrets.GH_APPLICATION_CLIENT_SECRET }}

